baseurl                  = "https://sjdh.us/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "0x738"
theme                    = "sam"
pygmentsStyle            = "fruity"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Nascent Dawn"

# Metadata for Open Graph and Twitter
#description          = "0x738"               # Max 160 characters show in search results
#images               = ["sam.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
#title                = "0x738"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[imaging]
    quality = 75
